---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: image-pull-secrets-controller
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
