---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: image-pull-secrets-controller
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: image-pull-secrets-controller
subjects:
- kind: ServiceAccount
  name: image-pull-secrets-controller
  namespace: kube-system
