name: docker-build

on:
  schedule:
  - cron:  '0 7 * * *'
  push:
    branches:
    - '**'
    tags:
    - 'v*.*.*'
  pull_request:

jobs:
  build:
    name: docker-build
    runs-on: ubuntu-20.04
    env:
      IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/image-pull-secrets-controller
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v3
      with:
        images: ${{ env.IMAGE_NAME }}
        tag-sha: true

    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        cache-from: ${{ env.IMAGE_NAME }}:${{ steps.docker_meta.outputs.version }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}

    - name: Run Trivy vulnerability scanner
      if: github.event_name != 'pull_request'
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.IMAGE_NAME }}:${{ steps.docker_meta.outputs.version }}
        format: 'template'
        template: '@/contrib/sarif.tpl'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: 'trivy-results.sarif'
