name: docker-build

on:
  push:
    branches:
    - master
  schedule:
  - cron:  '0 7 * * *'

jobs:
  build:
    name: docker-build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: nicholasdille/image-pull-secrets-controller
        tag-sha: true

    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build
      uses: docker/build-push-action@v2
      with:
        cache-from: nicholasdille/image-pull-secrets-controller:latest
        tags: nicholasdille/image-pull-secrets-controller:latest

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: nicholasdille/image-pull-secrets-controller:latest
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        cache-from: nicholasdille/image-pull-secrets-controller:latest
        push: true
        tags: nicholasdille/image-pull-secrets-controller:latest
